# Generated by Django 4.2.7 on 2025-10-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='source',
            field=models.CharField(default='cage', max_length=50),
        ),
        migrations.AlterField(
            model_name='egg',
            name='chicken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cages.chicken'),
        ),
    ]
