# Generated by Django 4.2.7 on 2025-10-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0003_expense_feedconsumption_feedpurchase_sale_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('feed', 'Feed Cost'), ('medicine', 'Medicine/Vaccination'), ('transport', 'Transport'), ('maintenance', 'Maintenance/Other')], max_length=20),
        ),
    ]
