# Generated by Django 4.2.7 on 2025-10-25 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cages', '0004_farmsettings_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='cage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egg',
            name='partition_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egg',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
