# Generated by Django 4.2.7 on 2025-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0005_egg_cage_id_egg_partition_index_egg_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='box_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
