# Generated by Django 4.2.7 on 2025-10-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cages', '0006_egg_box_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('treatment_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('medicine', 'Medicine'), ('checkup', 'Health Checkup'), ('treatment', 'Treatment')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('medication', models.CharField(blank=True, max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vet_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chicken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cages.chicken')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
