# Generated by Django 4.2.7 on 2025-10-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('owner', 'Owner')], default='worker', max_length=10),
        ),
    ]
