# Generated by Django 4.2.7 on 2025-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('owner', 'Owner'), ('admin', 'Admin')], default='worker', max_length=10),
        ),
    ]
